// <auto-generated />
using System;
using ApplicationManagementSystem.DataAccess.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationManagementSystem.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231231163826_mig_1_initial")]
    partial class mig_1_initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<int?>("DeletorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(12);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(11);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnOrder(6);

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95ec6f74-ff19-4e6b-8c2d-8ed2f37ada1f"),
                            Address = "784 Furman Street, Vaughn, Montana, 6667",
                            Birthday = new DateTime(1965, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1652),
                            Email = "tonihampton@valreda.com",
                            FirstName = "Toni",
                            IdentityNumber = "67890123456",
                            IsDeleted = false,
                            LastName = "Hampton",
                            Reason = "Aliqua sint nulla officia esse duis eiusmod enim qui. Fugiat minim deserunt nostrud labore dolore nulla occaecat ut laboris proident pariatur consectetur. ",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fc0e0f17-7bfc-40f5-9afb-ebe5c32be476"),
                            Address = "457 Roosevelt Place, Tilleda, Florida, 5976",
                            Birthday = new DateTime(1963, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1668),
                            Email = "erickacalderon@valreda.com",
                            FirstName = "Ericka",
                            IdentityNumber = "12345678902",
                            IsDeleted = false,
                            LastName = "Calderon",
                            Reason = "Voluptate ut proident eiusmod ea quis velit ad ut proident nisi. Qui ex ea laboris do in ullamco eiusmod ullamco reprehenderit ea adipisicing anim nulla.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("65cdca36-e3d9-45af-847e-f15486924ac3"),
                            Address = "767 Martense Street, Foxworth, Arizona, 3104",
                            Birthday = new DateTime(1977, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1728),
                            Email = "mamieengland@valreda.com",
                            FirstName = "Mamie",
                            IdentityNumber = "12345678903",
                            IsDeleted = false,
                            LastName = "England",
                            Reason = "Dolore esse ad cillum id commodo ut dolor laborum mollit mollit nisi exercitation aute ad.Quis veniam aliqua ipsum magna velit aliquip consequat id incididunt.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4f25fa33-b31f-4be8-8eda-1a754efb74c6"),
                            Address = "834 Halsey Street, Madaket, California, 7037",
                            Birthday = new DateTime(1975, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1734),
                            Email = "hopkinshuff@valreda.com",
                            FirstName = "Hopkins",
                            IdentityNumber = "12345678904",
                            IsDeleted = false,
                            LastName = "Huff",
                            Reason = "Nulla nostrud proident qui ad ea proident aliqua do. Ea in nisi velit in labore veniam enim mollit. Fugiat mollit voluptate amet incididunt non commodo ex. Est sint occaecat sint irure non esse sit commodo minim aute Lorem excepteur.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a4065f80-a496-4d90-8f79-884d2b18bb88"),
                            Address = "280 Clermont Avenue, Jugtown, Ohio, 7483",
                            Birthday = new DateTime(1972, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1739),
                            Email = "averymcdonald@valreda.com",
                            FirstName = "Avery",
                            IdentityNumber = "12345678905",
                            IsDeleted = false,
                            LastName = "Mcdonald",
                            Reason = "Nostrud ad qui deserunt elit sunt est dolor laborum nisi. Non adipisicing est dolore ut irure irure culpa aute voluptate cupidatat aliquip et.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("55777e3c-df5c-4f3a-8e37-a226297f46af"),
                            Address = "761 Hoyt Street, Gardiner, Iowa, 4576",
                            Birthday = new DateTime(1964, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1744),
                            Email = "hildabarnett@valreda.com",
                            FirstName = "Hilda",
                            IdentityNumber = "12345678906",
                            IsDeleted = false,
                            LastName = "Barnett",
                            Reason = "Pariatur aute sit excepteur id exercitation ad sit occaecat sunt eiusmod ea. Laboris ullamco laborum aliqua culpa voluptate in labore aliquip irure ea ex non commodo.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("da1907d8-2cf0-4a3d-a2ce-30838be5eb75"),
                            Address = "870 Clark Street, Thatcher, Virginia, 775",
                            Birthday = new DateTime(1982, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1749),
                            Email = "freemandaugherty@valreda.com",
                            FirstName = "Freeman",
                            IdentityNumber = "12345678907",
                            IsDeleted = false,
                            LastName = "Daugherty",
                            Reason = "Excepteur sint irure nostrud eu voluptate incididunt irure minim do ullamco adipisicing irure consequat enim. Reprehenderit nulla exercitation enim elit adipisicing sunt ex ad culpa ut.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aef9c2b2-7b9e-4a75-9634-717157036eaa"),
                            Address = "894 Osborn Street, Driftwood, Connecticut, 1546",
                            Birthday = new DateTime(2000, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1776),
                            Email = "haynesford@valreda.com",
                            FirstName = "Haynes",
                            IdentityNumber = "12345678908",
                            IsDeleted = false,
                            LastName = "Ford",
                            Reason = "Nostrud do aliqua magna pariatur exercitation anim labore amet magna adipisicing.Non enim eu reprehenderit proident ea reprehenderit incididunt occaecat incididunt ipsum. Ullamco nostrud ullamco ut magna mollit reprehenderit officia.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("17677fdf-de64-415b-a8c1-b8675f7a1800"),
                            Address = "124 Grattan Street, Monument, South Dakota, 5593",
                            Birthday = new DateTime(1996, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1781),
                            Email = "tanyaboyle@valreda.com",
                            FirstName = "Tanya",
                            IdentityNumber = "12345678909",
                            IsDeleted = false,
                            LastName = "Boyle",
                            Reason = "Laboris cupidatat tempor cupidatat eiusmod occaecat dolore commodo mollit et reprehenderit cupidatat qui elit occaecat. Amet cillum voluptate aliquip elit veniam Lorem commodo sint. Veniam velit irure esse veniam aliqua aliqua velit qui velit.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e27ab587-e897-4dda-b7dc-72876feba7b1"),
                            Address = "818 Ruby Street, Garnet, Alaska, 1235",
                            Birthday = new DateTime(1981, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1786),
                            Email = "caradurham@valreda.com",
                            FirstName = "Cara",
                            IdentityNumber = "12345678910",
                            IsDeleted = false,
                            LastName = "Durham",
                            Reason = "Laborum laboris consectetur aliqua laboris non. In in deserunt ut qui voluptate eiusmod. Magna irure elit eu eiusmod veniam adipisicing.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f21f40a9-6cd7-4911-b1a0-ff81b268e6a2"),
                            Address = "737 Provost Street, Odessa, Kentucky, 4490",
                            Birthday = new DateTime(1992, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1791),
                            Email = "dawsonpratt@valreda.com",
                            FirstName = "Dawson",
                            IdentityNumber = "12345678911",
                            IsDeleted = false,
                            LastName = "Pratt",
                            Reason = "Non Lorem exercitation est proident laborum sint est id amet officia eiusmod elit eiusmod. Ullamco veniam amet sunt aliqua tempor. Non minim consequat irure consequat sint. Sit aliquip non minim ea non magna non ex culpa aliqua ipsum sunt eiusmod.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ed83dfba-0577-4f60-b5cb-63acb8d492a5"),
                            Address = "635 Taaffe Place, Jeff, Idaho, 9876",
                            Birthday = new DateTime(1992, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1796),
                            Email = "perezcooke@valreda.com",
                            FirstName = "Perez",
                            IdentityNumber = "12345678912",
                            IsDeleted = false,
                            LastName = "Cooke",
                            Reason = "Dolore cillum commodo irure in dolore irure pariatur culpa eiusmod. Aliqua velit consequat labore elit magna adipisicing laborum ipsum.Velit nostrud deserunt consequat minim culpa est. Tempor et Lorem et consequat ipsum cupidatat consectetur dolor minim id enim.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d1254620-51e8-4401-82a6-a065ca88c0d0"),
                            Address = "202 Midwood Street, Barstow, Mississippi, 6264",
                            Birthday = new DateTime(1967, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1801),
                            Email = "powerslynn@valreda.com",
                            FirstName = "Powers",
                            IdentityNumber = "12345678913",
                            IsDeleted = false,
                            LastName = "Lynn",
                            Reason = "Nulla labore id commodo et quis consectetur. Nisi ipsum cupidatat cillum consequat exercitation voluptate laboris. Ex culpa cillum sit officia qui velit.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bdda0546-b013-45f0-b6df-6c9e5ee6d77d"),
                            Address = "460 Chauncey Street, Roosevelt, Pennsylvania, 1055",
                            Birthday = new DateTime(1976, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1806),
                            Email = "jodiewilliams@valreda.com",
                            FirstName = "Jodie",
                            IdentityNumber = "12345678914",
                            IsDeleted = false,
                            LastName = "Williams",
                            Reason = "Mollit ullamco fugiat reprehenderit sunt culpa. Dolore sint eiusmod ad ullamco sint consectetur dolor elit sint occaecat ipsum. Quis esse sunt Lorem irure pariatur do ullamco cillum non amet labore aliqua eu. Deserunt dolore in voluptate officia sunt eu sint adipisicing minim pariatur.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fb4772dc-f75a-4454-8ea0-0ad60fa09091"),
                            Address = "475 Landis Court, Coultervillle, Missouri, 2696",
                            Birthday = new DateTime(1999, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1811),
                            Email = "francespeck@valreda.com",
                            FirstName = "Frances",
                            IdentityNumber = "12345678915",
                            IsDeleted = false,
                            LastName = "Peck",
                            Reason = "Aliquip excepteur sint magna mollit dolor exercitation ex. Laboris aute nisi fugiat minim proident ut. In incididunt Lorem id aliquip incididunt dolor pariatur quis cupidatat elit ullamco mollit nulla. Cillum laborum laborum elit tempor. Ut consectetur aute anim Lorem.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ebd010bf-8dba-4df4-a749-e239dd7da619"),
                            Address = "305 Schermerhorn Street, Boykin, Minnesota, 307",
                            Birthday = new DateTime(1999, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2023, 12, 31, 19, 38, 25, 735, DateTimeKind.Local).AddTicks(1822),
                            Email = "puckettoneill@valreda.com",
                            FirstName = "Puckett",
                            IdentityNumber = "12345678916",
                            IsDeleted = false,
                            LastName = "Oneill",
                            Reason = "Tempor commodo nulla voluptate cupidatat amet magna dolor laboris occaecat incididunt. Eu velit proident laborum elit reprehenderit enim mollit occaecat excepteur in ex eu. Incididunt anim elit consequat sunt cupidatat tempor aliquip nostrud occaecat nisi et adipisicing esse nulla.",
                            Response = "",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emredindr@gmail.com",
                            Name = "Emre",
                            Password = "asd123",
                            PhoneNumber = "1234567890",
                            Role = 1,
                            Surname = "Dindar",
                            Username = "emredindr"
                        },
                        new
                        {
                            Id = 2,
                            Email = "kodluyoruz@patika.dev",
                            Name = "DevPatika",
                            Password = "bootcamp109",
                            PhoneNumber = "1234567890",
                            Role = 2,
                            Surname = "Kodluyoruz",
                            Username = "kodluyoruz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
