// <auto-generated />
using System;
using ApplicationManagementSystem.DataAccess.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationManagementSystem.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240127124831_initial_migration")]
    partial class initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(15);

                    b.Property<int?>("DeletorUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(14);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int")
                        .HasColumnOrder(13);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnOrder(6);

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(9);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fec832d4-7696-4a72-a149-38cb6ff52735"),
                            Address = "784 Furman Street, Vaughn, Montana, 6667",
                            Birthday = new DateTime(1965, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(359),
                            Email = "tonihampton@valreda.com",
                            FirstName = "Toni",
                            IdentityNumber = "67890123456",
                            IsDeleted = false,
                            LastName = "Hampton",
                            Reason = "Aliqua sint nulla officia esse duis eiusmod enim qui. Fugiat minim deserunt nostrud labore dolore nulla occaecat ut laboris proident pariatur consectetur. ",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0700e751-9c0a-457c-8f9b-68b9d6d1303c"),
                            Address = "457 Roosevelt Place, Tilleda, Florida, 5976",
                            Birthday = new DateTime(1963, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(371),
                            Email = "erickacalderon@valreda.com",
                            FirstName = "Ericka",
                            IdentityNumber = "12345678902",
                            IsDeleted = false,
                            LastName = "Calderon",
                            Reason = "Voluptate ut proident eiusmod ea quis velit ad ut proident nisi. Qui ex ea laboris do in ullamco eiusmod ullamco reprehenderit ea adipisicing anim nulla.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("387b8da4-40cb-437a-a4af-0a3343dcf82a"),
                            Address = "767 Martense Street, Foxworth, Arizona, 3104",
                            Birthday = new DateTime(1977, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(376),
                            Email = "mamieengland@valreda.com",
                            FirstName = "Mamie",
                            IdentityNumber = "12345678903",
                            IsDeleted = false,
                            LastName = "England",
                            Reason = "Dolore esse ad cillum id commodo ut dolor laborum mollit mollit nisi exercitation aute ad.Quis veniam aliqua ipsum magna velit aliquip consequat id incididunt.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("63adfc83-8315-4bfb-af79-09540aacccc6"),
                            Address = "834 Halsey Street, Madaket, California, 7037",
                            Birthday = new DateTime(1975, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(381),
                            Email = "hopkinshuff@valreda.com",
                            FirstName = "Hopkins",
                            IdentityNumber = "12345678904",
                            IsDeleted = false,
                            LastName = "Huff",
                            Reason = "Nulla nostrud proident qui ad ea proident aliqua do. Ea in nisi velit in labore veniam enim mollit. Fugiat mollit voluptate amet incididunt non commodo ex. Est sint occaecat sint irure non esse sit commodo minim aute Lorem excepteur.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("867513f1-e68e-4b6a-90cc-55b2ef950704"),
                            Address = "280 Clermont Avenue, Jugtown, Ohio, 7483",
                            Birthday = new DateTime(1972, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(408),
                            Email = "averymcdonald@valreda.com",
                            FirstName = "Avery",
                            IdentityNumber = "12345678905",
                            IsDeleted = false,
                            LastName = "Mcdonald",
                            Reason = "Nostrud ad qui deserunt elit sunt est dolor laborum nisi. Non adipisicing est dolore ut irure irure culpa aute voluptate cupidatat aliquip et.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("adc7e0ae-1fb6-4f7a-9d27-aa14370dc923"),
                            Address = "761 Hoyt Street, Gardiner, Iowa, 4576",
                            Birthday = new DateTime(1964, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(414),
                            Email = "hildabarnett@valreda.com",
                            FirstName = "Hilda",
                            IdentityNumber = "12345678906",
                            IsDeleted = false,
                            LastName = "Barnett",
                            Reason = "Pariatur aute sit excepteur id exercitation ad sit occaecat sunt eiusmod ea. Laboris ullamco laborum aliqua culpa voluptate in labore aliquip irure ea ex non commodo.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("36b21b04-0a1f-4e68-8d08-dea46b597970"),
                            Address = "870 Clark Street, Thatcher, Virginia, 775",
                            Birthday = new DateTime(1982, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(419),
                            Email = "freemandaugherty@valreda.com",
                            FirstName = "Freeman",
                            IdentityNumber = "12345678907",
                            IsDeleted = false,
                            LastName = "Daugherty",
                            Reason = "Excepteur sint irure nostrud eu voluptate incididunt irure minim do ullamco adipisicing irure consequat enim. Reprehenderit nulla exercitation enim elit adipisicing sunt ex ad culpa ut.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e9d925fb-54e0-443b-8334-bbdba3f69b0d"),
                            Address = "894 Osborn Street, Driftwood, Connecticut, 1546",
                            Birthday = new DateTime(2000, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(424),
                            Email = "haynesford@valreda.com",
                            FirstName = "Haynes",
                            IdentityNumber = "12345678908",
                            IsDeleted = false,
                            LastName = "Ford",
                            Reason = "Nostrud do aliqua magna pariatur exercitation anim labore amet magna adipisicing.Non enim eu reprehenderit proident ea reprehenderit incididunt occaecat incididunt ipsum. Ullamco nostrud ullamco ut magna mollit reprehenderit officia.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3bca0f99-29ad-4cfe-8c40-a9f93fcf5787"),
                            Address = "124 Grattan Street, Monument, South Dakota, 5593",
                            Birthday = new DateTime(1996, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(429),
                            Email = "tanyaboyle@valreda.com",
                            FirstName = "Tanya",
                            IdentityNumber = "12345678909",
                            IsDeleted = false,
                            LastName = "Boyle",
                            Reason = "Laboris cupidatat tempor cupidatat eiusmod occaecat dolore commodo mollit et reprehenderit cupidatat qui elit occaecat. Amet cillum voluptate aliquip elit veniam Lorem commodo sint. Veniam velit irure esse veniam aliqua aliqua velit qui velit.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0c6374a9-6226-4929-ac1d-81b574676303"),
                            Address = "818 Ruby Street, Garnet, Alaska, 1235",
                            Birthday = new DateTime(1981, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(434),
                            Email = "caradurham@valreda.com",
                            FirstName = "Cara",
                            IdentityNumber = "12345678910",
                            IsDeleted = false,
                            LastName = "Durham",
                            Reason = "Laborum laboris consectetur aliqua laboris non. In in deserunt ut qui voluptate eiusmod. Magna irure elit eu eiusmod veniam adipisicing.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1a6a7160-71a9-4203-99f7-5b6b0f206e98"),
                            Address = "737 Provost Street, Odessa, Kentucky, 4490",
                            Birthday = new DateTime(1992, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(439),
                            Email = "dawsonpratt@valreda.com",
                            FirstName = "Dawson",
                            IdentityNumber = "12345678911",
                            IsDeleted = false,
                            LastName = "Pratt",
                            Reason = "Non Lorem exercitation est proident laborum sint est id amet officia eiusmod elit eiusmod. Ullamco veniam amet sunt aliqua tempor. Non minim consequat irure consequat sint. Sit aliquip non minim ea non magna non ex culpa aliqua ipsum sunt eiusmod.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fffa87b7-2419-4289-bc4a-b788771d52ff"),
                            Address = "635 Taaffe Place, Jeff, Idaho, 9876",
                            Birthday = new DateTime(1992, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(444),
                            Email = "perezcooke@valreda.com",
                            FirstName = "Perez",
                            IdentityNumber = "12345678912",
                            IsDeleted = false,
                            LastName = "Cooke",
                            Reason = "Dolore cillum commodo irure in dolore irure pariatur culpa eiusmod. Aliqua velit consequat labore elit magna adipisicing laborum ipsum.Velit nostrud deserunt consequat minim culpa est. Tempor et Lorem et consequat ipsum cupidatat consectetur dolor minim id enim.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("eeab568b-d16d-457e-a028-57772bfba2ee"),
                            Address = "202 Midwood Street, Barstow, Mississippi, 6264",
                            Birthday = new DateTime(1967, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(456),
                            Email = "powerslynn@valreda.com",
                            FirstName = "Powers",
                            IdentityNumber = "12345678913",
                            IsDeleted = false,
                            LastName = "Lynn",
                            Reason = "Nulla labore id commodo et quis consectetur. Nisi ipsum cupidatat cillum consequat exercitation voluptate laboris. Ex culpa cillum sit officia qui velit.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3d2eda47-f6f6-4f87-a236-06c4e2fa737e"),
                            Address = "460 Chauncey Street, Roosevelt, Pennsylvania, 1055",
                            Birthday = new DateTime(1976, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(461),
                            Email = "jodiewilliams@valreda.com",
                            FirstName = "Jodie",
                            IdentityNumber = "12345678914",
                            IsDeleted = false,
                            LastName = "Williams",
                            Reason = "Mollit ullamco fugiat reprehenderit sunt culpa. Dolore sint eiusmod ad ullamco sint consectetur dolor elit sint occaecat ipsum. Quis esse sunt Lorem irure pariatur do ullamco cillum non amet labore aliqua eu. Deserunt dolore in voluptate officia sunt eu sint adipisicing minim pariatur.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b4a5c3af-34e2-4272-b906-df16d0362b41"),
                            Address = "475 Landis Court, Coultervillle, Missouri, 2696",
                            Birthday = new DateTime(1999, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(465),
                            Email = "francespeck@valreda.com",
                            FirstName = "Frances",
                            IdentityNumber = "12345678915",
                            IsDeleted = false,
                            LastName = "Peck",
                            Reason = "Aliquip excepteur sint magna mollit dolor exercitation ex. Laboris aute nisi fugiat minim proident ut. In incididunt Lorem id aliquip incididunt dolor pariatur quis cupidatat elit ullamco mollit nulla. Cillum laborum laborum elit tempor. Ut consectetur aute anim Lorem.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("18ad013b-bf99-4898-80f2-3799d0d305e8"),
                            Address = "305 Schermerhorn Street, Boykin, Minnesota, 307",
                            Birthday = new DateTime(1999, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(470),
                            Email = "puckettoneill@valreda.com",
                            FirstName = "Puckett",
                            IdentityNumber = "12345678916",
                            IsDeleted = false,
                            LastName = "Oneill",
                            Reason = "Tempor commodo nulla voluptate cupidatat amet magna dolor laboris occaecat incididunt. Eu velit proident laborum elit reprehenderit enim mollit occaecat excepteur in ex eu. Incididunt anim elit consequat sunt cupidatat tempor aliquip nostrud occaecat nisi et adipisicing esse nulla.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7f03ed2d-19db-473d-9216-c9221b370153"),
                            Address = "378 Lott Avenue, Teasdale, Illinois, 1860",
                            Birthday = new DateTime(1981, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(475),
                            Email = "mccoyclarke@valreda.com",
                            FirstName = "Mccoy",
                            IdentityNumber = "12345678917",
                            IsDeleted = false,
                            LastName = "Clarke",
                            Reason = "Aliqua mollit sint in elit adipisicing dolore pariatur veniam ut laborum consequat. Pariatur est ipsum deserunt in. Minim labore amet est veniam occaecat sit anim. Aliqua culpa enim quis dolor nulla cupidatat. Non elit exercitation et deserunt incididunt veniam. Sit mollit esse laborum Lorem eiusmod irure cillum sint consequat minim qui minim.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("af77d19a-d1a2-4252-b1ed-0d3696eca3e7"),
                            Address = "167 Preston Court, Ada, Nebraska, 7066",
                            Birthday = new DateTime(1981, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(480),
                            Email = "mccarthymartin@valreda.com",
                            FirstName = "Mccarthy",
                            IdentityNumber = "12345678918",
                            IsDeleted = false,
                            LastName = "Martin",
                            Reason = "Proident commodo veniam commodo voluptate ad nisi. Amet qui nisi reprehenderit ex elit nostrud. Eu quis aliqua laborum labore dolore elit. Non consectetur nostrud aliqua sit culpa excepteur. Nostrud culpa cillum sit ad quis aliqua anim ullamco sit nisi et duis ad cupidatat. Dolore elit ipsum consectetur cupidatat magna. Anim officia dolor magna occaecat id.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fab13530-8151-433b-b34b-fc5b7703bdb6"),
                            Address = "275 Landis Court, Fontanelle, Marshall Islands, 4084",
                            Birthday = new DateTime(1974, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(485),
                            Email = "carrollcarrillo@valreda.com",
                            FirstName = "Carroll",
                            IdentityNumber = "12345678919",
                            IsDeleted = false,
                            LastName = "Carrillo",
                            Reason = "Ipsum occaecat esse cupidatat occaecat tempor. Minim quis in laboris dolore reprehenderit in occaecat esse fugiat excepteur veniam. Voluptate fugiat ex ex pariatur non sint nostrud exercitation sunt deserunt. Tempor ipsum minim amet non laborum labore ullamco duis veniam. Fugiat voluptate anim excepteur anim veniam ut voluptate eiusmod occaecat. Anim reprehenderit magna nisi est nisi sunt non minim cupidatat quis do officia et. Magna adipisicing fugiat labore ea mollit sunt deserunt anim aliquip ea ut ad dolor in.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c373ee45-b7bc-45b9-b0aa-eae8f1ff2a7e"),
                            Address = "300 Roosevelt Court, Linganore, Arizona, 9378",
                            Birthday = new DateTime(1980, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(490),
                            Email = "milespearson@valreda.com",
                            FirstName = "Miles",
                            IdentityNumber = "12345678920",
                            IsDeleted = false,
                            LastName = "Pearson",
                            Reason = "Ex non quis qui nulla elit dolore anim do magna. Cupidatat non exercitation cupidatat labore sit nisi do duis. Aliqua Lorem excepteur nisi nisi aute minim.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ed8d5cf6-9dde-4033-b245-186ed96ec829"),
                            Address = "295 Harman Street, Forbestown, Pennsylvania, 6491",
                            Birthday = new DateTime(1966, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(499),
                            Email = "randipace@valreda.com",
                            FirstName = "Randi",
                            IdentityNumber = "12345678921",
                            IsDeleted = false,
                            LastName = "Pace",
                            Reason = "Dolor fugiat labore do incididunt mollit deserunt aliquip ad sunt mollit sint. Sunt deserunt quis nisi do adipisicing mollit et enim eiusmod. Deserunt nisi ut cillum reprehenderit consectetur cupidatat in ex duis et.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("04ad583c-104b-4d21-929b-48c0539e5987"),
                            Address = "123 Guernsey Street, Marenisco, Montana, 2971",
                            Birthday = new DateTime(1999, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(504),
                            Email = "candaceburton@valreda.com",
                            FirstName = "Candace",
                            IdentityNumber = "12345678922",
                            IsDeleted = false,
                            LastName = "Burton",
                            Reason = "Eiusmod labore voluptate tempor duis deserunt laborum minim nisi minim qui reprehenderit. Ut in in mollit do irure elit ullamco est. Incididunt minim ea fugiat aute enim ipsum eu cupidatat non occaecat aliquip. Occaecat mollit adipisicing occaecat qui id esse id exercitation.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8df0ef50-0e8e-41bf-b7c0-a1f5ace64b8b"),
                            Address = "779 Poly Place, Welch, Delaware, 5670",
                            Birthday = new DateTime(1991, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(508),
                            Email = "karlalittle@valreda.com",
                            FirstName = "Karla",
                            IdentityNumber = "12345678923",
                            IsDeleted = false,
                            LastName = "Little",
                            Reason = "Do amet Lorem laborum ad cupidatat do enim officia. In voluptate aute laborum Lorem occaecat fugiat. Aliquip id enim qui fugiat deserunt laboris dolor incididunt adipisicing officia consequat. Est nisi non ad est proident cillum nulla proident magna.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4277e296-2277-4df5-a281-8c8e39892fc9"),
                            Address = "406 Ferris Street, Kempton, Nevada, 8511",
                            Birthday = new DateTime(1989, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(513),
                            Email = "helenaherrera@valreda.com",
                            FirstName = "Helena",
                            IdentityNumber = "12345678924",
                            IsDeleted = false,
                            LastName = "Herrera",
                            Reason = "Ullamco cillum id nostrud ipsum esse quis velit velit est. Id est sunt enim nisi irure nulla do incididunt sint Lorem ad. Laboris nostrud sunt irure incididunt aute incididunt ipsum elit sit tempor commodo quis.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("10945b81-c84e-454d-baed-08f72e452911"),
                            Address = "616 Louisa Street, Ona, Massachusetts, 2957",
                            Birthday = new DateTime(1998, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(518),
                            Email = "josefacarpenter@valreda.com",
                            FirstName = "Josefa",
                            IdentityNumber = "12345678925",
                            IsDeleted = false,
                            LastName = "Carpenter",
                            Reason = "Est laboris consectetur deserunt esse elit fugiat irure qui sint. Veniam minim exercitation non nisi proident eiusmod et excepteur. Deserunt cupidatat cillum duis officia quis quis proident. Id sunt non Lorem cillum ipsum id tempor aliquip amet fugiat nulla et sunt Lorem. Velit excepteur reprehenderit eu voluptate ex commodo irure consectetur ad id. Ipsum mollit ipsum in incididunt commodo. Commodo mollit do magna dolor.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ea7e77e6-655f-48bb-ab9a-f9ebaff04be0"),
                            Address = "155 Hale Avenue, Alden, Oregon, 4793",
                            Birthday = new DateTime(1997, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(523),
                            Email = "nelsonmorgan@valreda.com",
                            FirstName = "Nelson",
                            IdentityNumber = "12345678926",
                            IsDeleted = false,
                            LastName = "Morgan",
                            Reason = "Tempor in est aliquip excepteur est. Id dolore est excepteur voluptate proident consectetur elit non ad id nostrud pariatur labore anim. Esse magna ex ut consequat exercitation est.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f3f733ea-0dca-4883-ace4-8c686a32c6e2"),
                            Address = "895 Kane Street, Hasty, Virgin Islands, 1394",
                            Birthday = new DateTime(1960, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(528),
                            Email = "rileylambert@valreda.com",
                            FirstName = "Riley",
                            IdentityNumber = "12345678927",
                            IsDeleted = false,
                            LastName = "Lambert",
                            Reason = "Et veniam incididunt enim veniam ipsum elit id. Labore dolore incididunt voluptate adipisicing ullamco non. Esse minim ut minim cillum enim proident aliquip cupidatat aliquip esse esse elit tempor. Laborum irure magna et anim irure officia reprehenderit occaecat adipisicing amet ea elit. Culpa sunt fugiat voluptate excepteur consectetur dolore aute.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("058b4c97-4188-4f2c-b700-2425ace63103"),
                            Address = "329 Howard Alley, Noblestown, Northern Mariana Islands, 8023",
                            Birthday = new DateTime(1962, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(532),
                            Email = "valentinekerr@valreda.com",
                            FirstName = "Valentine",
                            IdentityNumber = "12345678928",
                            IsDeleted = false,
                            LastName = "Kerr",
                            Reason = "Deserunt aute labore deserunt commodo. Commodo consectetur dolore laborum dolore anim officia mollit mollit amet. Duis anim voluptate non deserunt esse eu esse ad laboris. Occaecat mollit mollit veniam officia ullamco nisi amet. Tempor laboris veniam officia enim in aliquip qui irure labore aliqua. Nostrud anim do ea mollit enim exercitation laborum commodo consectetur laboris consequat. Anim consequat cillum exercitation laborum qui proident sunt nisi excepteur qui.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2e1ddce4-0928-4f19-be96-038e386364b2"),
                            Address = "423 Bulwer Place, Williston, Oklahoma, 9490",
                            Birthday = new DateTime(1980, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(542),
                            Email = "chandlerstein@valreda.com",
                            FirstName = "Chandler",
                            IdentityNumber = "12345678929",
                            IsDeleted = false,
                            LastName = "Stein",
                            Reason = "Sint dolore voluptate ea commodo nostrud consequat duis cupidatat reprehenderit. Labore irure est cillum aute anim voluptate consectetur magna consequat elit adipisicing. Laboris occaecat magna id labore exercitation dolore voluptate in sit fugiat voluptate aute ea. Tempor cupidatat voluptate enim aliquip eu aliquip dolore non proident. Consectetur tempor pariatur magna laboris. Magna pariatur ad sit irure nostrud cupidatat culpa.",
                            Response = "",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f9171101-2364-439b-9f58-91391fa84514"),
                            Address = "221 Corbin Place, Jennings, Utah, 323",
                            Birthday = new DateTime(1969, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2024, 1, 27, 15, 48, 31, 331, DateTimeKind.Local).AddTicks(547),
                            Email = "robbiesantana@valreda.com",
                            FirstName = "Robbie",
                            IdentityNumber = "12345678930",
                            IsDeleted = false,
                            LastName = "Santana",
                            Reason = "Eu qui cupidatat in cillum culpa deserunt amet dolor mollit aliquip. Excepteur quis ipsum exercitation non duis elit. Reprehenderit ut laboris excepteur id aliquip ullamco nisi proident consectetur ex laborum exercitation veniam. Velit eiusmod laborum officia reprehenderit nisi deserunt est labore. Id nisi dolor laboris labore ex in anim commodo aliqua. Qui fugiat amet nostrud eu est ipsum ipsum cupidatat magna.",
                            Response = "",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ApplicationManagementSystem.Core.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emredindr@gmail.com",
                            Name = "Emre",
                            Password = "asd123",
                            PhoneNumber = "1234567890",
                            Role = 1,
                            Surname = "Dindar",
                            Username = "emredindr"
                        },
                        new
                        {
                            Id = 2,
                            Email = "kodluyoruz@patika.dev",
                            Name = "DevPatika",
                            Password = "bootcamp109",
                            PhoneNumber = "1234567890",
                            Role = 2,
                            Surname = "Kodluyoruz",
                            Username = "kodluyoruz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
